export default function TermsPage() {
  return (
    <div className="legal-page">
      <h1>Terms of Service</h1>
      <p className="legal-meta">Effective date: April 2025 &nbsp;·&nbsp; Last updated: April 2025</p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        By accessing or using valyu ("the Service", "we", "us"), you agree to be bound by these Terms of
        Service. If you do not agree, please do not use the Service.
      </p>

      <h2>2. What valyu Is</h2>
      <p>
        valyu is an AI-powered equity research platform that generates informational reports on companies
        listed on the National Stock Exchange of India (NSE). Reports are assembled automatically from
        publicly available data and AI language models. The Service is provided free of charge for
        personal, non-commercial use.
      </p>

      <h2>3. Not Investment Advice</h2>
      <p>
        <strong>valyu is not a SEBI-registered investment adviser, research analyst, or portfolio manager.</strong>{' '}
        Nothing on this platform — including reports, market data, analysis, flags, or any other content —
        constitutes investment advice, a recommendation, or an offer or solicitation to buy or sell any
        security. You are solely responsible for your own investment decisions. Always consult a
        SEBI-registered investment adviser before making financial decisions.
      </p>

      <h2>4. AI-Generated Content Disclaimer</h2>
      <p>
        Reports are generated by AI language models that process publicly available financial data.
        AI-generated content may contain errors, omissions, or outdated information. valyu makes no
        representation as to the accuracy, completeness, or timeliness of any report. You should
        independently verify all information before relying on it.
      </p>

      <h2>5. Eligibility</h2>
      <p>
        You must be at least 18 years old to use the Service. By using valyu, you represent that you meet
        this requirement and that your use complies with all applicable laws in your jurisdiction.
      </p>

      <h2>6. User Accounts</h2>
      <p>
        The Service uses Google OAuth for authentication. You are responsible for maintaining the security
        of your Google account. We may suspend or terminate access for accounts that violate these terms
        or are used for abuse.
      </p>

      <h2>7. Rate Limits &amp; Acceptable Use</h2>
      <ul>
        <li>Report generation is limited to 10 reports per user per day.</li>
        <li>You may not use automated scripts, bots, or crawlers to access the Service.</li>
        <li>You may not reverse-engineer, scrape, or reproduce our platform or its data pipeline.</li>
        <li>You may not attempt to circumvent rate limits or authentication.</li>
      </ul>

      <h2>8. Prohibited Uses</h2>
      <ul>
        <li>Redistributing or reselling reports for commercial gain.</li>
        <li>Using reports to manipulate securities markets or spread misinformation.</li>
        <li>Using the Service in any manner that violates applicable laws, including SEBI regulations.</li>
        <li>Impersonating another person or entity.</li>
      </ul>

      <h2>9. Intellectual Property</h2>
      <p>
        All content, design, and code on valyu is owned by or licensed to us. You are granted a limited,
        non-exclusive, non-transferable licence to access and use reports for your own personal,
        non-commercial research. No content may be republished, sold, or sub-licensed without written
        permission.
      </p>

      <h2>10. Limitation of Liability</h2>
      <p>
        To the fullest extent permitted by law, valyu and its operators shall not be liable for any
        investment losses, financial damages, or any direct, indirect, incidental, or consequential
        damages arising from your use of the Service. As the Service is provided free of charge, our
        maximum aggregate liability to you is ₹0.
      </p>

      <h2>11. Indemnification</h2>
      <p>
        You agree to indemnify and hold harmless valyu and its operators from any claims, losses, or
        expenses (including legal fees) arising from your misuse of the Service or violation of these
        Terms.
      </p>

      <h2 id="compliance">12. Compliance &amp; Regulatory Disclosures</h2>
      <p>
        valyu is <strong>not</strong> registered with SEBI, AMFI, RBI, or any other financial regulator.
        We do not hold any licence to provide investment advice or portfolio management services.
      </p>
      <ul>
        <li>Past performance of any company or sector is not indicative of future results.</li>
        <li>Financial data is sourced from public filings (BSE/NSE, annual reports, exchange disclosures).</li>
        <li>Concall summaries are derived from publicly available earnings call transcripts.</li>
        <li>Market index data (Nifty 50, Sensex, Nifty Bank) is sourced from Yahoo Finance and may be delayed.</li>
      </ul>

      <h2 id="disclosures">13. Disclosures</h2>
      <ul>
        <li>valyu has no financial interest in any company covered in its reports.</li>
        <li>Reports are generated on demand and are not the product of a human research analyst.</li>
        <li>AI models used may have knowledge cut-off dates; recent events may not be reflected.</li>
        <li>
          We may partner with or use third-party services (OpenAI, Neon, Vercel, Google) in delivering
          the Service. These relationships do not influence report content.
        </li>
      </ul>

      <h2>14. Governing Law</h2>
      <p>
        These Terms are governed by and construed in accordance with the laws of India. Any disputes
        shall be subject to the exclusive jurisdiction of the courts of Bengaluru, Karnataka.
      </p>

      <h2>15. Changes to These Terms</h2>
      <p>
        We may update these Terms from time to time. Changes will be posted on this page with an updated
        effective date. Continued use of the Service after changes constitutes your acceptance of the
        revised Terms.
      </p>

      <h2>16. Contact</h2>
      <div className="legal-contact">
        <p>
          For questions about these Terms, please contact us at:{' '}
          <a href="mailto:investment.research50@gmail.com">investment.research50@gmail.com</a>
        </p>
      </div>
    </div>
  )
}
