import { useState, useCallback, useRef, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { suggest, getMarketIndices, type SymbolSuggestion, type IndexTick } from './api'
import { trackEvent } from './analytics'
import {
  INDICES as STATIC_INDICES,
  REVIEWS,
  FEATURES,
  HOW_IT_WORKS,
  STATS,
  POPULAR_STOCKS,
} from './landingData'

const DEBOUNCE_MS = 280
const CAROUSEL_MS = 5000
const REFRESH_MS = 60_000

export default function Landing() {
  const [query, setQuery] = useState('')
  const [suggestions, setSuggestions] = useState<SymbolSuggestion[]>([])
  const [loading, setLoading] = useState(false)
  const [open, setOpen] = useState(false)
  const [highlight, setHighlight] = useState(0)
  const [reviewIndex, setReviewIndex] = useState(0)
  const [indices, setIndices] = useState<IndexTick[]>(STATIC_INDICES)
  const navigate = useNavigate()
  const debounceRef = useRef<ReturnType<typeof setTimeout>>()
  const listRef = useRef<HTMLUListElement>(null)

  useEffect(() => {
    let cancelled = false
    const load = async () => {
      try {
        const data = await getMarketIndices()
        if (!cancelled && data.length > 0) {
          setIndices((prev) => {
            const liveMap = new Map(data.map((d: IndexTick) => [d.name, d]))
            return prev.map((p) => liveMap.get(p.name) ?? p)
          })
        }
      } catch {
        /* keep static fallback */
      }
    }
    load()
    const timer = setInterval(load, REFRESH_MS)
    return () => {
      cancelled = true
      clearInterval(timer)
    }
  }, [])

  const fetchSuggestions = useCallback(async (q: string) => {
    if (!q.trim()) {
      setSuggestions([])
      return
    }
    setLoading(true)
    try {
      const list = await suggest(q)
      setSuggestions(list)
      setHighlight(0)
      setOpen(true)
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    if (debounceRef.current) clearTimeout(debounceRef.current)
    debounceRef.current = setTimeout(() => fetchSuggestions(query), DEBOUNCE_MS)
    return () => {
      if (debounceRef.current) clearTimeout(debounceRef.current)
    }
  }, [query, fetchSuggestions])

  useEffect(() => {
    const t = setInterval(() => {
      setReviewIndex((i) => (i + 1) % REVIEWS.length)
    }, CAROUSEL_MS)
    return () => clearInterval(t)
  }, [])

  const select = (s: SymbolSuggestion) => {
    setOpen(false)
    trackEvent('Report Requested', { symbol: s.symbol })
    navigate(`/${encodeURIComponent(s.symbol)}/report`)
  }

  const goToStock = (symbol: string) => {
    trackEvent('Popular Stock Clicked', { symbol })
    navigate(`/${encodeURIComponent(symbol)}/report`)
  }

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (!open || suggestions.length === 0) {
      if (e.key === 'Enter' && query.trim()) fetchSuggestions(query.trim())
      return
    }
    if (e.key === 'ArrowDown') {
      e.preventDefault()
      setHighlight((h) => (h < suggestions.length - 1 ? h + 1 : 0))
      return
    }
    if (e.key === 'ArrowUp') {
      e.preventDefault()
      setHighlight((h) => (h > 0 ? h - 1 : suggestions.length - 1))
      return
    }
    if (e.key === 'Enter') {
      e.preventDefault()
      select(suggestions[highlight])
      return
    }
    if (e.key === 'Escape') {
      setOpen(false)
    }
  }

  useEffect(() => {
    listRef.current
      ?.querySelector(`[data-index="${highlight}"]`)
      ?.scrollIntoView({ block: 'nearest' })
  }, [highlight])

  const review = REVIEWS[reviewIndex]

  return (
    <div className="landing">
      {/* ── Market Ticker ── */}
      <div className="landing-ticker">
        <div className="landing-ticker-inner">
          {indices.map((idx) => (
            <span key={idx.name} className="landing-ticker-item">
              <span className="ticker-name">{idx.name}</span>
              <span className="ticker-value">{idx.value}</span>
              <span className={`ticker-change ${idx.positive ? 'up' : 'down'}`}>
                {idx.change}
              </span>
            </span>
          ))}
        </div>
      </div>

      {/* ── Hero ── */}
      <section className="landing-hero">
        <span className="hero-badge">AI-POWERED EQUITY RESEARCH</span>
        <h1 className="hero-title">
          Institutional-Grade Analysis
          <br />
          <span className="hero-title-accent">for Every Investor</span>
        </h1>
        <p className="hero-subtitle">
          Comprehensive research reports on 4,000+ NSE-listed companies, generated by 7 parallel AI
          research agents in under 2 minutes.
        </p>

        <div className="search-wrap">
          <div className="search-inner">
            <svg className="search-icon" viewBox="0 0 20 20" fill="currentColor" aria-hidden>
              <path
                fillRule="evenodd"
                d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                clipRule="evenodd"
              />
            </svg>
            <input
              type="text"
              className="search-input"
              placeholder="Search by company name or symbol (e.g. RELIANCE)"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              onFocus={() => suggestions.length > 0 && setOpen(true)}
              onBlur={() => setTimeout(() => setOpen(false), 200)}
              onKeyDown={handleKeyDown}
              aria-label="Search stocks"
              aria-autocomplete="list"
              aria-expanded={open}
              aria-controls="suggestions-list"
              id="search-input"
            />
            {loading && <span className="search-spinner" aria-hidden />}
          </div>
          {open && suggestions.length > 0 && (
            <ul
              id="suggestions-list"
              ref={listRef}
              className="suggestions-list"
              role="listbox"
              aria-label="Stock suggestions"
            >
              {suggestions.map((s, i) => (
                <li
                  key={`${s.symbol}-${i}`}
                  role="option"
                  data-index={i}
                  aria-selected={i === highlight}
                  className={`suggestion-item ${i === highlight ? 'highlight' : ''}`}
                  onMouseDown={(e) => {
                    e.preventDefault()
                    select(s)
                  }}
                >
                  <span className="suggestion-symbol">{s.symbol}</span>
                  <span className="suggestion-name">{s.name}</span>
                  <span className="suggestion-badge">NSE</span>
                </li>
              ))}
            </ul>
          )}
        </div>

        <div className="hero-popular">
          <span className="hero-popular-label">Popular:</span>
          {POPULAR_STOCKS.map((s) => (
            <button
              key={s}
              type="button"
              className="hero-popular-chip"
              onClick={() => goToStock(s)}
            >
              {s}
            </button>
          ))}
        </div>
      </section>

      {/* ── Stats Strip ── */}
      <section className="landing-stats" aria-label="Key statistics">
        <div className="stats-inner">
          {STATS.map((s) => (
            <div key={s.label} className="stat-item">
              <span className="stat-value">{s.value}</span>
              <span className="stat-label">{s.label}</span>
            </div>
          ))}
        </div>
      </section>

      {/* ── How It Works ── */}
      <section className="landing-how" aria-label="How it works">
        <h2 className="section-heading">How It Works</h2>
        <p className="section-subheading">
          From search to report in three simple steps
        </p>
        <div className="how-grid">
          {HOW_IT_WORKS.map((step, i) => (
            <div key={step.number} className="how-card">
              <span className="how-number">{step.number}</span>
              <h3 className="how-title">{step.title}</h3>
              <p className="how-desc">{step.description}</p>
              {i < HOW_IT_WORKS.length - 1 && (
                <span className="how-arrow" aria-hidden>
                  →
                </span>
              )}
            </div>
          ))}
        </div>
      </section>

      {/* ── Features ── */}
      <section className="landing-features" aria-label="Research modules">
        <h2 className="section-heading">What's in a Report</h2>
        <p className="section-subheading">
          Each report is assembled from 7 specialized research modules running in parallel
        </p>
        <div className="features-grid">
          {FEATURES.map((f) => (
            <div key={f.title} className="feature-card">
              <span className="feature-icon" aria-hidden>
                {f.icon}
              </span>
              <h3 className="feature-title">{f.title}</h3>
              <p className="feature-desc">{f.description}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── Reviews ── */}
      <section className="landing-reviews" aria-label="User reviews">
        <h2 className="section-heading">What Analysts Say</h2>
        <div className="review-card">
          <div className="review-stars" aria-label="5 stars">
            {'★★★★★'}
          </div>
          <blockquote className="review-quote">"{review.quote}"</blockquote>
          <footer className="review-footer">
            <div className="review-avatar">
              {review.author.charAt(0)}
            </div>
            <div className="review-meta">
              <strong>{review.author}</strong>
              <span className="review-role">{review.role}</span>
            </div>
          </footer>
        </div>
        <div className="review-dots">
          {REVIEWS.map((_, i) => (
            <button
              key={i}
              type="button"
              className={`review-dot ${i === reviewIndex ? 'active' : ''}`}
              onClick={() => setReviewIndex(i)}
              aria-label={`Review ${i + 1}`}
            />
          ))}
        </div>
      </section>

      {/* ── CTA ── */}
      <section className="landing-cta" aria-label="Call to action">
        <h2 className="cta-heading">Ready to Research?</h2>
        <p className="cta-subtitle">
          Search any NSE-listed stock above and get a complete equity research report — free.
        </p>
        <button
          type="button"
          className="cta-btn"
          onClick={() => document.getElementById('search-input')?.focus()}
        >
          Start Analyzing
        </button>
      </section>
    </div>
  )
}
